version: '3'
services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - app-network
      
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/custom.cnf:/etc/mysql/conf.d/custom.cnf'
    ports:
      - 3307:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  php:
    build: ./build/php
    image: php:7-fpm
    volumes:
      - './php.ini:/usr/local/etc/php/php.ini'
      - './php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - '/Users/casey/Desktop/projects/wp-5/www:/var/www'
      - ~/.drush/:/root/.drush/
    working_dir: /var/www
    networks:
      - app-network
      
  apache:
    image: httpd:latest
    container_name: apache
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 8081:80
    volumes:
      - '/Users/casey/Desktop/projects/wp-5/www:/var/www'
      - './httpd.conf:/usr/local/apache2/conf/httpd.conf'
      - './apache:/usr/local/apache2/sites-enabled'
      - './logs/apache:/logs'
    networks:
        - app-network

  # drupal:
  #   image: php:7.2-apache
  #   build: ./build/php
  #   container_name: apache
  #   restart: unless-stopped
  #   ports:
  #     - 8081:80
  #   volumes:
  #     - '/Users/casey/Desktop/projects/wp-5/www:/var/www'
  #     # - './httpd.conf:/etc/apache2/apache2.conf'
  #     - './apache:/etc/apache2/sites-enabled'
  #     - './logs/apache:/logs'
  #   networks:
  #       - app-network

  nginx:
    image: 'nginx'
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - db
      - apache
      - phpmyadmin
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - '/Users/casey/Desktop/projects/certs:/var/certs:ro'
      - '/Users/casey/Desktop/projects/nginx/nginx:/etc/nginx/conf.d'
      - '/Users/casey/Desktop/projects/nginx/shared:/etc/nginx/shared'
      - '/Users/casey/Desktop/projects/wp-5/www:/var/www'
    networks:
        - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_VERBOSE=db
      - PMA_ABSOLUTE_URI=https://phpmyadmin.local
    links:
      - db
    volumes:
      - './php.ini:/usr/local/etc/php/php.ini'
      - './pma/sessions:/sessions'
      - './pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
      - './db/data:/db'
    ports:
      - 8080:8080
    networks:
        - app-network


  # drush:
  #   image: drush/drush:9
  #   container_name: drush
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - './php.ini:/usr/local/etc/php/php.ini'
  #     - './php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
  #     - '/Users/casey/Desktop/projects/wp-5/www:/var/www'
  #   links:
  #     - db
  #     - nginx
  #     - apache
  #   extra_hosts:
  #     - "portal.local:127.0.0.1"
  #   entrypoint:
  #     - drush
  #     - "--root=/var/www/galdermacapcom-master-fea73447b5bf46105300481c49aa5d0e59e378cc/docroot"
  #     - "--uri=http://portal.local"
  #   networks:
  #       - app-network

networks:
  app-network:
    driver: bridge  