version: '3'
services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/custom.cnf:/etc/mysql/conf.d/custom.cnf'
    ports:
      - 3307:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  php:
    build: ./build/php
    image: php:7-fpm
    restart: unless-stopped
    volumes:
      - './php/php.ini:/usr/local/etc/php/php.ini'
      - './php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - ~/.drush/:/root/.drush/
      - './www:/var/www'
    working_dir: /var/www
    networks:
      - app-network
      
  apache:
    image: httpd:latest
    container_name: apache
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 8081:80
    volumes:
      - './apache/httpd.conf:/usr/local/apache2/conf/httpd.conf'
      - './apache/sites:/usr/local/apache2/sites-enabled'
      - './logs/apache:/logs'
      - './www:/var/www'
    networks:
        - app-network

  nginx:
    image: 'nginx'
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - db
      - php
      - apache
      - phpmyadmin
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - './certs:/var/certs:ro'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './www:/var/www'
    networks:
        - app-network

  nginx2:
    build: './build/nginx'
    container_name: nginx2
    depends_on:
      - db
      - php
      - apache
      - phpmyadmin
    networks:
        - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_VERBOSE=db
      - PMA_ABSOLUTE_URI=https://phpmyadmin.local
    links:
      - db
    volumes:
      - './php/php.ini:/usr/local/etc/php/php.ini'
      - './pma/sessions:/sessions'
      - './pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
      - './db/data:/db'
    ports:
      - 8080:8080
    networks:
        - app-network

# volumes:
#   www-sync:
#     external: true

networks:
  app-network:
    driver: bridge  
